### ISSUE TITLE
Not enough complexity

### ISSUE THREAD

**Issue by jaylaw81** [philduffy/ie8-rip#1]
I think your leaving yourself open to a few security holes... should be running this behind SSL with nodejs as well.

**Comment by jennschiffer** [comment]
+1

**Comment by jennschiffer** [comment]
what's the status on this

**Comment by willmanduffy** [comment]
Waiting for Rust 2.0

**Comment by willmanduffy** [comment]
we did it ie8 died 311 (the number of the beast)  days ago.

http://www.ie8.rip
